@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "reader@email.com",
  "password": "123456"
}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "publisher",
  "email": "publisher@email.com",
  "password": "123456",
  "avatarUrl": "urldaimagem"
}

### Get one user
# @name getUserByToken
GET {{baseUrl}}/user/profile
Authorization: Bearer {{jwtToken}}

### Create Story
# @name createStory
POST {{baseUrl}}/story
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "title": "The fire sword",
  "coverUrl": "https://example.com/covers/fire-sword.jpg",
  "storyType": "original",
  "synopsis": "here are the synopsis od the story",
  "tags": ["acao", "aventura", "drama"],
  "mainGenre": "fantasy",
  "language": "english"
}

### Find One Story by slug
# @name findStoryBySlug
GET {{baseUrl}}/story/The-fire-sword-a1mxd6

### Find All Stories with pagination and filtering
# @name findAllStoriesPaginatedAndFiltered
GET {{baseUrl}}/story?page=1&limit=2&storyType=original&&sortOrder=ASC

### Find All Stories with pagination
# @name findAllStoriesPaginated
GET {{baseUrl}}/story?page=1&limit=2

### Update Story
# @name updateStory
PATCH {{baseUrl}}/story/5cdd27a8-9820-44a3-aa45-2164121cb543
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "title": "Hobbits resolve 1",
  "synopsis": "here are the synopsis od the story"
}

### Delete Story
DELETE {{baseUrl}}/story/05350656-0bf1-4175-85f4-59c9aa1c68a9
Authorization: Bearer {{jwtToken}}

### Get user stories
# @name getUserStories
GET {{baseUrl}}/story/me
Authorization: Bearer {{jwtToken}}

### Create Volume
# @name createVolume
POST {{baseUrl}}/volume/create/ed14c3be-4831-432f-b461-03bfcc351cfc
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "title": "Volume 1 of fire sword",
  "description": "Here is the description of volume 1 of fire sword"
}

### Update Volume
PATCH  {{baseUrl}}/volume/fde43722-2a18-44e4-b26d-900d10949f9c
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "description": "Here is the description of volume 1"
}

### Get Volume by Id
# @name getVolumeById
GET {{baseUrl}}/volume/9ec8bc40-aeda-4564-b2ff-f7cfb8a52538
Authorization: Bearer {{jwtToken}}

### Get Volumes by Story
# @name getVolumesByStory
GET {{baseUrl}}/volume/all/25d8d2f0-a3e6-4ae4-b385-0be9f67d51d5
Authorization: Bearer {{jwtToken}}

### Delete Volume
# @name deleteVolume
DELETE {{baseUrl}}/volume/db69f898-5396-4cd1-962e-1d2be8626254
Authorization: Bearer {{jwtToken}}

### Create Chapter
# @name createChapter
POST {{baseUrl}}/chapter/create/52ad5743-54e4-4107-a387-2d5774a3eeb0
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
   "title": "chaper 4 fire sword",
   "content": "Here is the content of fire sword",
   "isDraft": true
}

### Get Chapters by Volume
# @name getChaptersByVolume
GET {{baseUrl}}/chapter/volume/52ad5743-54e4-4107-a387-2d5774a3eeb0
Authorization: Bearer {{jwtToken}}

### Get All story chapter with numbers
# @name getChaptersByVolume
GET {{baseUrl}}/chapter/story/25d8d2f0-a3e6-4ae4-b385-0be9f67d51d5/all
Authorization: Bearer {{jwtToken}}

### Get Chapter by Id
# @name getChapterById
GET {{baseUrl}}/chapter/123acb61-cabd-4465-943e-3f75647f8b1e
Authorization: Bearer {{jwtToken}}

### Reorder chapter
PATCH {{baseUrl}}/chapter/123acb61-cabd-4465-943e-3f75647f8b1e/reorder
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "beforeChapterId": "089be7fd-9c39-479c-80dd-5196303d1f12",
  "afterChapterId": "75b8492f-2c70-42a4-865e-8569629717fb"
}


### Update Chapter
PATCH {{baseUrl}}/chapter/546d5f5a-c81a-40d8-a7b2-d816c1fbf666
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "content": "Here is the updated content of chapter 1 updated"
}

### Delete Chapter
DELETE {{baseUrl}}/chapter/f4bfea94-9845-434b-9b41-b20b78c71c78
Authorization: Bearer {{jwtToken}}

### Create Announcement (Publisher)
# @name createAnnouncement
POST {{baseUrl}}/announcement
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "title": "Segundo anúncio",
  "image": "https://example.com/image.jpg",
  "content": "Conteúdo do anúncio."
}

### Announcement - Buscar por id (Pública)
# @name getAnnouncementById
GET {{baseUrl}}/announcement/3df3d2e7-bbd0-4d5e-acf9-3cf616b92e8b

### Announcement - Buscar todos ativos (Pública)
# @name getActiveAnnouncements
GET {{baseUrl}}/announcement

### Announcement - Buscar todos (Publisher) 
# @name getAllAnnouncements
GET {{baseUrl}}/announcement/all?page=2&limit=5
Authorization: Bearer {{jwtToken}}

### Announcement - Atualizar (Publisher)
# @name updateAnnouncement
PATCH {{baseUrl}}/announcement/3df3d2e7-bbd0-4d5e-acf9-3cf616b92e8b
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "isActive": true
}

### Announcement - Deletar (Publisher)
# @name deleteAnnouncement
DELETE {{baseUrl}}/announcement/74d7a246-c9f7-48b8-9ada-a1710b1b8483
Authorization: Bearer {{jwtToken}}


### Create Highlight
# @name createHighlight
POST {{baseUrl}}/highlight
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "title": "Highlight Title 7",
  "banner": "https://example.com/banner.jpg",
  "link": "https://example.com"
}

### Get all Highlights (Public)
# @name getAllHighlights
GET {{baseUrl}}/highlight
Authorization: Bearer {{jwtToken}}

### Get Highlight by Id (Public)
# @name getHighlightById
GET {{baseUrl}}/highlight/d32976a2-db29-4c53-8115-0420aeeb0a9a
Authorization: Bearer {{jwtToken}}

### Get all Highlights (Publisher)
# @name getAllHighlightsPublisher
GET {{baseUrl}}/highlight/all
Authorization: Bearer {{jwtToken}}

### Update Highlight (Publisher)
# @name updateHighlight
PATCH {{baseUrl}}/highlight/d32976a2-db29-4c53-8115-0420aeeb0a9a
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "isActive": true
}

### Delete Highlight
# @name deleteHighlight
DELETE {{baseUrl}}/highlight/aa6ecd26-195d-41ee-9719-ed4e2dcecbca
Authorization: Bearer {{jwtToken}}

### Ver todos os progressos de leitura
# @name readingProgress
GET {{baseUrl}}/reading-progress
Authorization: Bearer {{jwtToken}}

### Progresso de leitura
# @name readingProgress
PATCH {{baseUrl}}/reading-progress
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "storyId": "25d8d2f0-a3e6-4ae4-b385-0be9f67d51d5",
  "chapterId": "1d87db20-40e6-4611-bd39-44c7937a2b96",
  "force": true
}

### Adicionar história à library
# @name addToLibrary
POST {{baseUrl}}/library/add
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "storyId": "25d8d2f0-a3e6-4ae4-b385-0be9f67d51d5"
}

### Remover história da library
# @name removeFromLibrary
DELETE {{baseUrl}}/library/remove
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "storyId": "<ID_DA_STORY_AQUI>"
}

### Remover várias histórias da library
# @name removeManyFromLibrary
DELETE {{baseUrl}}/library/remove-many
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "storyIds": ["<ID1>", "<ID2>"]
}

### Listar todas as histórias da library do usuário
# @name getLibrary
GET {{baseUrl}}/library
Authorization: Bearer {{jwtToken}}

### create comment in storie
# @name postStorieComment
POST {{baseUrl}}/comment
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "body": "Show de bola ewrrwr!",
  "targetType": "story",
  "targetId": "ed14c3be-4831-432f-b461-03bfcc351cfc",
  "rating": {
    "writingQuality": 5,
    "updateStability": 4,
    "plotDevelopment": 4,
    "charactersBuilding": 4,
    "worldBuilding": 5
  }
}

### create comment in chapter
# @name postChapterComment
POST {{baseUrl}}/comment
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "body": "Que capitulo 2 incrivel",
  "targetType": "chapter",
  "targetId": "da953afd-0d2a-47c0-9fef-050885667838"
}

### create comment in annoucement
# @name postAnoucemmetnComment
POST {{baseUrl}}/comment
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "body": "Que anuncio incrivel",
  "targetType": "annoucement",
  "targetId": "3df3d2e7-bbd0-4d5e-acf9-3cf616b92e8b"
}

### get target comments
# @name getTargetWithComments
GET {{baseUrl}}/comment/story/ed14c3be-4831-432f-b461-03bfcc351cfc
Authorization: Bearer {{jwtToken}}

### update comment by id
# @name updateComment
PUT {{baseUrl}}/comment/ac5ace03-28e2-4117-a551-815cbc0462df
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "body": "Show de bola editado 3"
}

### update rating by story ID
# @name updateRating
PUT {{baseUrl}}/rating/ed14c3be-4831-432f-b461-03bfcc351cfc
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "writingQuality": 5,
  "updateStability": 5,
  "plotDevelopment": 5,
  "charactersBuilding": 5,
  "worldBuilding": 5
}

### get user rating by story ID
# @name updateRating
GET {{baseUrl}}/rating/ed14c3be-4831-432f-b461-03bfcc351cfc
Authorization: Bearer {{jwtToken}}

### delete user comment by comment ID
# @name deleteComment
DELETE  {{baseUrl}}/comment/ac5ace03-28e2-4117-a551-815cbc0462df
Authorization: Bearer {{jwtToken}}
